### GET
GET http://localhost:8087/data
Accept: application/json

### POST
POST http://localhost:8087/data
Content-Type: application/json

{
  "pvVoltage" : 1,
  "pvElectricCurrent" : 2,
  "pvOutput" : 3,
  "outputVoltage" : 4,
  "outputElectricCurrent" :  5,
  "currentOutput" : 6,
  "frequency" :  7,
  "powerFactor": 10,
  "cumulativePowerGeneration" : 8,
  "breakdown" : 9
}

### DELETE

DELETE http://localhost:8080/all

### GET
GET http://192.168.43.136:8080/data
Accept: application/json